### ISSUE TITLE
Semantic premises of the library

### ISSUE THREAD

**Issue by Nettsentrisk** [bolatovumar/captionify#2]
I'd like to point a few semantic issues with how this library is meant to be used.

1. The alt attribute is not meant to be the same thing as a caption. An alt attribute is meant to be a text that would replace the image if there were not an image there, if that makes sense in the context the image is appearing. A caption is used to describe an image, not to replace its purpose. In some cases the alt attribute might be appropriate for a caption, must most of the time that won't be the case. For this reason something other than the alt attribute should probably be used to generate the figcaption text. The title attribute may often be more in line with what a caption would say, but again, these are not 1:1 semantically, either.

2. Figures for all images? The figure element is meant to be used in specific contexts, not as an appropriate container for all images no matter where they appear. A figure is a figure, that is, something that can be cited to from somewhere else, and can live on its own. Assuming that all images can/should be in figures I think is an assumption that does not take the semantic context into consideration.

**Comment by bolatovumar** [comment]
Thanks for your feedback. I will leave some thoughts in relation to your comments below.

1. Your are absolutely correct about the purpose of the alt attribute. That's why Captionify allows for captions to be specified via a custom data-caption HTML attribute if alt attribute does not seem like a good choice. The reason alt attribute is used for caption text is because I first used an early version of Captionify while working on my personal site the content of which is written entirely in markdown. I wanted to have an easy way to caption images appearing in certain sections of the site while writing standard markdown.

2. Again, you are right about the figure tag. I made the decision to use figure and figcaption tags based on their in a jQuery plugin of similar nature (and also for compatibility purposes with a caption styling CSS package which reliies on the figure and figcaption duo). It might be a good idea add an option for specifying exactly what tag should be used to wrap the image and the caption. Or maybe replace the figure and figcaption tags with divs.

**Comment by luck2011** [comment]
1. So, custom attribute could be used as a fallback. If people have their alt attribute useful for some other purpose, they could give their caption by custom attribute just like 'data-caption', and the code should check this attribute firstly.

**Comment by bolatovumar** [comment]
Makes sense.  I might change it so that data-caption attribute is checked
first and alt attribute is used as a fallback. This might not be necessary
though since users can already pass a 'dataCaption: true' option if they
don't want to use alt attributes for captions.

**Comment by bolatovumar** [comment]
Also, I'm not sure how much the whole semantics argument matters in this case since HTML source doesn't change and therefore the semantics of the original document remains the same, it's just the DOM that changes.

**Comment by luck2011** [comment]
“users can already pass a 'dataCaption: true' option”
Great, I think your solution is better.
